name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.REPO_TOKEN }}" | docker login ghcr.io -u "aswinsunil" --password-stdin

      - name: Build Docker Image locally
        run: docker build -t ghcr.io/aswinsunil/task-manager:latest .       

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/aswinsunil/task-manager:latest

      - name: Update GitOps repo
        uses: actions/checkout@v2
        with:
          repository: yourusername/gitops-repo
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          path: gitops

      - name: Update image tag in deployment
        run: |
          cd gitops/task-manager
          sed -i 's|image: .*|image: yourdockerhubusername/task-manager:latest|' deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update image tag to latest"
          git push
